# Generated by Django 4.0.4 on 2023-01-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
