# Generated by Django 4.0.4 on 2023-04-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoid',
            name='speaker',
            field=models.CharField(default='me', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoid',
            name='title',
            field=models.CharField(default='testing', max_length=200),
            preserve_default=False,
        ),
    ]
