# Generated by Django 4.0.4 on 2023-02-16 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_alter_picture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='role',
        ),
        migrations.AddField(
            model_name='picture',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
